apiVersion: v1
kind: Service
metadata:
  name: netcat-service
  namespace: broadvoice
spec:
  type: ClusterIP
  selector:
    app: netcat
  ports:
    - protocol: TCP
      port: 5060
      targetPort: 5060
